CompileFlags:
  CompilationDatabase: build
  Compiler: clang++
  Add:
    - -std=c++23
    - -stdlib=libc++
    - -fuse-ld=lld
    - -Wall
    - -Wextra
    - -Wpedantic
    - -IC:\LLEdge\bolt\include
    - -IC:\LLEdge\clang\include
    - -IC:\LLEdge\clang-tools-extra\clang-apply-replacements\include
    - -IC:\LLEdge\clang-tools-extra\include-cleaner\include
    - -IC:\LLEdge\compiler-rt\include
    - -IC:\LLEdge\flang\include
    - -IC:\LLEdge\flang-rt\include
    - -IC:\LLEdge\libc\include
    - -IC:\LLEdge\libclc\clc\include
    - -IC:\LLEdge\libclc\opencl\include
    - -IC:\LLEdge\libcxx\include
    - -IC:\LLEdge\libcxx\src\include
    - -IC:\LLEdge\libcxx\src\experimental\include
    - -IC:\LLEdge\libcxxabi\include
    - -IC:\LLEdge\libsycl\include
    - -IC:\LLEdge\libunwind\include
    - -IC:\LLEdge\lld\include
    - -IC:\LLEdge\lldb\include
    - -IC:\LLEdge\llvm\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\bolt\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\clang\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\clang-tools-extra\pseudo\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\compiler-rt\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\libcxx\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\libcxxabi\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\lld\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\lldb\include
    - -IC:\LLEdge\llvm\utils\gn\secondary\llvm\include
    - -IC:\LLEdge\mlir\include
    - -IC:\LLEdge\offload\include
    - -IC:\LLEdge\openmp\device\include
    - -IC:\LLEdge\openmp\runtime\src\include
    - -IC:\LLEdge\orc-rt\include
    - -IC:\LLEdge\polly\include
    - -IC:\LLEdge\third-party\benchmark\include
    - -IC:\LLEdge\third-party\boost-math\include
    - -IC:\LLEdge\third-party\siphash\include
    - -IC:\LLEdge\third-party\unittest\googlemock\include
    - -IC:\LLEdge\third-party\unittest\googletest\include
    - -IC:\LLEdge\utils\bazel\llvm-project-overlay\clang\include
    - -IC:\LLEdge\utils\bazel\llvm-project-overlay\flang\include
    - -IC:\LLEdge\utils\bazel\llvm-project-overlay\libc\test\include
    - -IC:\LLEdge\utils\bazel\llvm-project-overlay\llvm\include
    - -I/lledge/bolt/include
    - -I/lledge/clang/include
    - -I/lledge/clang-tools-extra/clang-apply-replacements/include
    - -I/lledge/clang-tools-extra/include-cleaner/include
    - -I/lledge/compiler-rt/include
    - -I/lledge/flang/include
    - -I/lledge/flang-rt/include
    - -I/lledge/libc/include
    - -I/lledge/libclc/clc/include
    - -I/lledge/libclc/opencl/include
    - -I/lledge/libcxx/include
    - -I/lledge/libcxx/src/include
    - -I/lledge/libcxx/src/experimental/include
    - -I/lledge/libcxxabi/include
    - -I/lledge/libsycl/include
    - -I/lledge/libunwind/include
    - -I/lledge/lld/include
    - -I/lledge/lldb/include
    - -I/lledge/llvm/include
    - -I/lledge/llvm/utils/gn/secondary/bolt/include
    - -I/lledge/llvm/utils/gn/secondary/clang/include
    - -I/lledge/llvm/utils/gn/secondary/clang-tools-extra/pseudo/include
    - -I/lledge/llvm/utils/gn/secondary/compiler-rt/include
    - -I/lledge/llvm/utils/gn/secondary/libcxx/include
    - -I/lledge/llvm/utils/gn/secondary/libcxxabi/include
    - -I/lledge/llvm/utils/gn/secondary/lld/include
    - -I/lledge/llvm/utils/gn/secondary/lldb/include
    - -I/lledge/llvm/utils/gn/secondary/llvm/include
    - -I/lledge/mlir/include
    - -I/lledge/offload/include
    - -I/lledge/openmp/device/include
    - -I/lledge/openmp/runtime/src/include
    - -I/lledge/orc-rt/include
    - -I/lledge/polly/include
    - -I/lledge/third-party/benchmark/include
    - -I/lledge/third-party/boost-math/include
    - -I/lledge/third-party/siphash/include
    - -I/lledge/third-party/unittest/googlemock/include
    - -I/lledge/third-party/unittest/googletest/include
    - -I/lledge/utils/bazel/llvm-project-overlay/clang/include
    - -I/lledge/utils/bazel/llvm-project-overlay/flang/include
    - -I/lledge/utils/bazel/llvm-project-overlay/libc/test/include
    - -I/lledge/utils/bazel/llvm-project-overlay/llvm/include